Repository thismeme-team/thismeme-web, pull requests merged in 2023-05, with the labels that each got.

#22 💄 style : 밈 결과가 없을때 UI 디자인 반영
  public/icon/memeChannel.svg
  src/components/common/Icon/assets.ts
  src/components/explore/EmptyMemesView/EmptyMemesView.tsx
Labels: design

#21 ♻️ refactor : 즐겨찾기 UI 및 로직 분리
  src/application/hooks/api/tags/index.ts
  src/components/tags/TagCategory/CategoryContent.tsx
  src/components/tags/TagCategory/CategoryTitle.tsx
  src/components/tags/TagCategory/FavoriteCategory.tsx
  src/components/tags/TagCategory/SlotCategory.tsx
  src/infra/api/tags/index.ts
Labels: refactor

#29 Resolve: Issue#26 Issue#27
  public/google0f21533cc94d63a5.html
  src/components/common/Modal/SignUpModal/SignUpModal.tsx
Labels: bug, setting

#24 💄 Style: 검색 창, 검색 페이지 디자인 반영
  mocks/handlers/search/index.ts
  mocks/handlers/tags/index.ts
  src/application/hooks/api/tags/index.ts
  src/application/hooks/common/useColoredText.tsx
  src/application/hooks/domain/search/useRecentSearch/useRecentSearch.ts
  src/components/common/Navigation/ExplorePageNavigation.tsx
  src/components/common/Navigation/IntroPageNavigation.tsx
  src/components/common/Navigation/MemeDetailPageNavigation.tsx
  src/components/common/Navigation/SearchPageNavigation.tsx
  src/components/common/Navigation/index.ts
  src/components/common/PullToRefresh/PullToRefresh.tsx
  src/components/common/PullToRefresh/RefreshContent.tsx
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchItem/SearchItem.tsx
  src/components/search/SearchPopular/SearchPopularItem.tsx
  src/components/search/SearchPopular/SearchPopularList.tsx
  src/components/search/SearchRecent/SearchRecent.tsx
  src/components/search/Skeleton/SkeletonTagList.tsx
  src/components/tags/TagCategory/TagCategory.tsx
  src/pages/explore/keywords/index.tsx
  src/pages/explore/tags/[tagId].tsx
  src/pages/index.tsx
  src/pages/memes/[id].tsx
  src/pages/search/index.tsx
Labels: design

#31 🔀 Merge: Develop으로 merge
  public/google0f21533cc94d63a5.html
  src/components/common/Modal/SignUpModal/SignUpModal.tsx
Labels: chore

#23 feat: dynamic og 이미지 구현
  .pnp.cjs
  .yarn/cache/@resvg-resvg-wasm-npm-2.4.1-78feafa3c1-855aa1e5f1.zip
  .yarn/cache/@shuding-opentype.js-npm-1.4.0-beta.0-498d62cde8-af3478c40c.zip
  .yarn/cache/@vercel-og-npm-0.5.3-c734504904-efe8588faf.zip
  .yarn/cache/base64-js-npm-0.0.8-f2946f7960-e95d2fa4b9.zip
  .yarn/cache/camelize-npm-1.0.1-d86ebe085a-91d8611d09.zip
  .yarn/cache/css-background-parser-npm-0.1.0-d1e94221f7-cf53bef8d5.zip
  .yarn/cache/css-box-shadow-npm-1.0.0-3-2a025ab419-1b7f15b291.zip
  .yarn/cache/css-color-keywords-npm-1.0.0-fc176df58b-8f125e3ad4.zip
  .yarn/cache/css-to-react-native-npm-3.2.0-46e31a25e3-263be65e80.zip
  .yarn/cache/emoji-regex-npm-10.2.1-463e5e2567-1aa2d16881.zip
  .yarn/cache/fflate-npm-0.7.4-df9245ab05-b812ab2604.zip
  .yarn/cache/linebreak-npm-1.1.0-d845ecba6a-65cb66900b.zip
  .yarn/cache/pako-npm-0.2.9-c88ac0d326-055f9487cd.zip
  .yarn/cache/satori-npm-0.4.9-d045a2f54e-4b616c81dc.zip
  .yarn/cache/string.prototype.codepointat-npm-0.2.1-82003deaf5-bafa15844d.zip
  .yarn/cache/tiny-inflate-npm-1.0.3-a7419a5c65-4086a1f893.zip
  .yarn/cache/unicode-trie-npm-2.0.0-54e0a4dd52-19e637ce20.zip
  .yarn/cache/yoga-wasm-web-npm-0.3.3-3f063ab1a0-ff65192a83.zip
  package.json
  public/open-graph/home.png
  src/application/util/constant.ts
  src/application/util/index.ts
  src/application/util/seo.ts
  src/components/common/NextSeo/NextSeo.tsx
  src/components/common/NextSeo/types.ts
  src/pages/api/og.tsx
  src/pages/explore/keywords/index.tsx
  src/pages/explore/tags/[tagId].tsx
  src/pages/index.tsx
  src/pages/memes/[id].tsx
  src/pages/search/index.tsx
  yarn.lock
Labels: feature

#25 ✨ 태그 북마크 버튼 토스트 및 디자인 수정
  src/components/common/PullToRefresh/PullToRefresh.tsx
  src/components/tags/TagCategory/CategoryContent.tsx
  src/components/tags/TagCategory/FavoriteCategory.tsx
  src/components/tags/TagFavoriteButton/TagBookmarkButton.tsx
Labels: feature, design

#33 :sparkles: Feat: 인기태그 대표이미지 api 연동
  src/application/hooks/api/tags/index.ts
  src/components/search/SearchPopular/SearchPopularItem.tsx
  src/components/search/SearchPopular/SearchPopularList.tsx
  src/infra/api/tags/index.ts
  src/infra/api/tags/types.ts
Labels: feature

#34 ✨ Feat: 헤더 애니메이션 적용, 스타일 버그 수정
  src/application/hooks/common/useScrollDirection.ts
  src/components/common/Navigation/BackButton/BackButton.tsx
  src/components/common/Navigation/ExplorePageNavigation.tsx
  src/components/common/Navigation/IntroPageNavigation.tsx
  src/components/common/Navigation/Logo/Logo.tsx
  src/components/tags/TagCategory/TagCategory.tsx
Labels: design

#32 :bug: Fix: 밈 api 무한요청 수정
  src/application/hooks/common/useIntersect.ts
Labels: bug

#28 Feat: 태그 검색 페이지 썸네일 구현
  mocks/handlers/search/index.ts
  src/application/hooks/api/search/index.ts
  src/application/util/constant.ts
  src/components/common/PullToRefresh/PullToRefresh.tsx
  src/components/explore/Thumbnail/Thumbnail.tsx
  src/components/explore/Thumbnail/index.ts
  src/components/explore/index.ts
  src/infra/api/search/index.ts
  src/pages/explore/tags/[tagId].tsx
  src/types/index.d.ts
Labels: feature

#39 🐛 fix: 메인 페이지 밈 중복 해결
  src/infra/api/meme/index.ts
Labels: bug, chore

#36 💄 1.5 릴리즈 QA
  mocks/handlers/tags/index.ts
  public/icon/memeChannel.svg
  src/components/common/Navigation/SideBar/LoginSideBarContent.tsx
  src/components/explore/EmptyMemesView/EmptyMemesView.tsx
  src/components/meme/MemeItem/MemeItem.tsx
  src/components/tags/TagCategory/CategoryContent.tsx
  src/components/tags/TagCategory/FavoriteCategory.tsx
  src/components/tags/TagCategory/TagCategory.tsx
  tailwind.config.js
Labels: design

#37 💄 PC 버전 디자인 추가
  public/img/serviceGuide.svg
  src/application/util/constant.ts
  src/components/common/ActionSheet/ActionSheet.tsx
  src/components/common/Drawer/Drawer.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/ServiceGuide.tsx
  src/components/common/Toast/ToastContainer.tsx
  src/components/search/SearchPopular/SearchPopularList.tsx
  src/components/search/SearchResult/SearchResultList.tsx
  src/components/tags/TagCategory/SlotCategory.tsx
Labels: design

#50 ✨ feat : 공통 GTM trigger 설정
  src/components/common/Drawer/Drawer.tsx
  src/components/common/Navigation/SearchHeader/SearchHeader.tsx
  src/components/common/Navigation/SideBar/SideBar.tsx
  src/components/home/MemeListContainer/DropDown/MemeSortDropDown.tsx
  src/components/meme/ActionSheet/MemeActionSheet.tsx
  src/components/meme/MemeInfo/Button/ClipboardCopyButton.tsx
  src/components/meme/MemeInfo/Button/KakaoShareButton.tsx
  src/components/meme/MemeInfo/Button/NativeShareButton.tsx
  src/components/meme/MemeItem/MemeItem.tsx
  src/components/tags/TagCategory/TagCategory.tsx
Labels: feature

#51 ✨feat: 태그 카테고리, signup GTM trigger 연동
  src/components/common/Modal/SignUpModal/SignUpModal.tsx
  src/components/tags/TagCategory/CategoryContent.tsx
Labels: feature

#47 ✨ feat : 프로필 GA 태그 연동
  src/components/common/Navigation/SideBar/LoginSideBarContent.tsx
  src/pages/mypage/index.tsx
Labels: feature

#46 ✨ Feat: 밈 상세 GA 태그 연동
  src/application/hooks/domain/collection/useCollection.tsx
  src/components/meme/MemeInfo/Button/CollectionSaveButton.tsx
  src/components/meme/MemeInfo/DropDown/MemeExport.tsx
  src/components/meme/MemeInfo/MemeCTAList.tsx
  src/components/meme/MemeInfo/MemeTagList.tsx
Labels: feature

#49 ✨ feat : 검색 결과 페이지 GA 태그 연동
  src/components/explore/Thumbnail/Thumbnail.tsx
  src/components/tags/TagFavoriteButton/TagBookmarkButton.tsx
Labels: feature

#48 ✨ feat : 검색중 페이지 GA 태그 연동
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchItem/SearchItem.tsx
  src/components/search/SearchPopular/SearchPopularItem.tsx
  src/components/search/SearchRecent/SearchRecent.tsx
Labels: feature
