Repository thismeme-team/thismeme-web, pull requests merged in 2023-04, with the labels that each got.

#7 ❗️Hotfix: GA, GTM 코드 추가
  src/application/hooks/common/index.ts
  src/application/hooks/common/useAnalytics.ts
  src/application/util/gtag.ts
  src/application/util/index.ts
  src/infra/sdk/google.tsx
  src/infra/sdk/index.ts
  src/infra/sdk/maze.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/types/global.d.ts
Labels: feature

#6 ✨ [YW-367] 헤더 스크롤 적용
  src/application/hooks/api/core/useCoreInfiniteQuery.ts
  src/application/hooks/common/index.ts
  src/application/hooks/common/useScrollDirection.ts
  src/application/util/index.ts
  src/application/util/throttle.ts
  src/components/common/Drawer/Drawer.tsx
  src/components/common/Masonry/Masonry.tsx
  src/components/common/Navigation/Navigation.tsx
  src/components/common/Portal/Portal.tsx
  src/components/home/MemeListContainer/DropDown/MemeSortDropDown.tsx
  src/components/meme/InfiniteMemeList/InfiniteMemeList.tsx
  src/components/search/SearchInput/SearchInput.tsx
  src/pages/index.tsx
  src/pages/search/index.tsx
Labels: feature

#14 Feat: 태그 카테고리 Drawer 전역 상태, Drawer 컴포넌트 리팩터링
  src/application/hooks/common/index.ts
  src/application/hooks/common/useScrollLocker.ts
  src/components/common/Drawer/Drawer.tsx
  src/components/common/Drawer/context.tsx
  src/components/common/Navigation/SideBar/SideBar.tsx
  src/components/tags/TagCategory/TagCategory.tsx
  src/components/tags/TagCategory/context.tsx
  src/components/tags/TagCategory/index.ts
  src/pages/_app.tsx
Labels: feature, refactor

#12 ♻️ 즐겨찾기 태그 api , 추가/삭제 로직 반영
  mocks/handlers/tags/data.ts
  mocks/handlers/tags/index.ts
  src/application/hooks/api/tags/index.ts
  src/application/hooks/api/tags/queryKey.ts
  src/components/tags/TagCategory/CategoryContent.tsx
  src/components/tags/TagFavoriteButton/TagBookmarkButton.tsx
  src/infra/api/tags/index.ts
  src/infra/api/tags/types.ts
Labels: refactor

#10 ♻️ Refactor: useOverlay hook 구현 및 ActionSheet 컴포넌트 개선, MemeShareModal 디자인 수정
  src/application/hooks/common/index.ts
  src/application/hooks/common/useOverlay/OverlayController.tsx
  src/application/hooks/common/useOverlay/OverlayProvider.tsx
  src/application/hooks/common/useOverlay/index.ts
  src/application/hooks/common/useOverlay/types.ts
  src/application/hooks/common/useOverlay/useOverlay.tsx
  src/components/collect/Collection/Collection.tsx
  src/components/collect/SearchedCollection/SearchedCollection.tsx
  src/components/common/ActionSheet/ActionSheet.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/ProfileModal.tsx
  src/components/common/Overlay/Overlay.tsx
  src/components/common/Overlay/index.ts
  src/components/meme/ActionSheet/MemeActionSheet.tsx
  src/components/meme/ActionSheet/index.ts
  src/components/meme/InfiniteMemeList/InfiniteMemeList.tsx
  src/components/meme/LongPress/MemeLongPress.tsx
  src/components/meme/LongPress/MemeLongPressContainer.tsx
  src/components/meme/LongPress/index.ts
  src/components/meme/MemeInfo/Button/ClipboardCopyButton.tsx
  src/components/meme/MemeInfo/Button/KakaoShareButton.tsx
  src/components/meme/MemeInfo/Button/NativeShareButton.tsx
  src/components/meme/MemeInfo/MemeCTAList.tsx
  src/components/meme/MemeInfo/Modal/MemeShareModal.tsx
  src/components/meme/MemeItem/MemeItem.tsx
  src/components/meme/index.ts
  src/components/mypage/SummarizedCollection/SummarizedCollection.tsx
  src/pages/_app.tsx
Labels: feature, refactor
